{
	"schema_version": "1.4.0",
	"id": "GHSA-hjp3-5g2q-7jww",
	"modified": "2023-05-01T14:00:47Z",
	"published": "2023-05-01T14:00:47Z",
	"summary": "Race Condition leading to logging errors",
	"details": "In certain setups with threaded web servers, Audited's use of `Thread.current` can incorrectly attributed audits to the wrong user. \n\nFixed in 5.3.3. \n\nIn March, @convisoappsec noticed that the library in question had a Race Condition problem, which caused logs to be registered at times with different users than those who performed the genuine actions.\n\n- The first issue we identified was from November 2021: https://github.com/collectiveidea/audited/issues/601 \n- So the solution was implemented in the following Pull Request: https://github.com/collectiveidea/audited/pull/669 \n- And the feature was published in version 5.3.3: RELEASE: https://github.com/collectiveidea/audited/pull/671\n",
	"severity": [
		{
			"type": "CVSS_V3",
			"score": "CVSS:3.1/AV:N/AC:H/PR:L/UI:N/S:U/C:N/I:L/A:N"
		}
	],
	"affected": [
		{
			"package": {
				"ecosystem": "RubyGems",
				"name": "audited"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "4.0.0"
						},
						{
							"fixed": "5.3.3"
						}
					]
				}
			]
		}
	],
	"references": [
		{
			"type": "WEB",
			"url": "https://github.com/collectiveidea/audited/security/advisories/GHSA-hjp3-5g2q-7jww"
		},
		{
			"type": "WEB",
			"url": "https://github.com/collectiveidea/audited/issues/601"
		},
		{
			"type": "WEB",
			"url": "https://github.com/collectiveidea/audited/pull/669"
		},
		{
			"type": "WEB",
			"url": "https://github.com/collectiveidea/audited/pull/671"
		},
		{
			"type": "PACKAGE",
			"url": "https://github.com/collectiveidea/audited"
		}
	],
	"database_specific": {
		"cwe_ids": [],
		"github_reviewed": true,
		"github_reviewed_at": "2023-05-01T14:00:47Z",
		"nvd_published_at": null,
		"severity": "LOW"
	}
}
